### ISSUE TITLE
Is possiable to support whereSlug or whereSlugIn method?

### ISSUE THREAD

**Issue by iflamed** [balping/laravel-hashslug#7]
In some case, like below:
```php
$query->whereSlug('user_id', $slug)->whereSlugIn('category_id',[$slug1, $slug2, $slug3]);
```

**Comment by balping** [comment]
You can use the `decodeSlug()` function and then use any filtering you want.

**Comment by balping** [comment]
Also, there is the `findBySlug()` function, which is basically equivalent to what you want with `whereSlug`. And for the `whereSlugIn` part of your pseudo-code, you really should use decoded ids, since categories will have another sequence of slugs than users. So introducing whereSlugIn for a usecase as yours, it would just lead to confusion.
